alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias tabe='mvim'
alias psql='psql84 -h localhost'
alias tunnel='ssh -f gad -L 5432:localhost:5432 -N'
alias createdb='/opt/local/lib/postgresql84/bin/createdb -h localhost'
alias dropdb='/opt/local/lib/postgresql84/bin/dropdb -h localhost'